name: dam
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  logger: ^2.6.2
  path: ^1.9.1
  version: ^3.0.2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  very_good_analysis: ^10.1.0
